add lab3 of flegel dmitrii
MrsSbr/amm-java-9-91 pull request #114
Opened 2023-11-18 21:38 UTC by neuron1st

2023-11-23 20:41 UTC, MrsSbr requested changes
У вас микроправки и очень классное решение. Напишите мне, как исправите, я вам выдам следующую

2023-11-23 20:41 UTC, MrsSbr commented on group_9/flegel.dmitrii/lab3/pom.xml
> +                    <source>8</source>
вы старовер?

2023-11-23 20:41 UTC, MrsSbr commented on group_9/flegel.dmitrii/lab3/src/main/java/factory/ContainerAnalysis.java
> +    private static void performanceCheck(String collectionType, Collection<Part> collection) {
Мне очень нравится ваше решение, вы большой молодец. Единственный момент с тем, что одного прогона не достаточно. Это связано с "прогревом" jvm и статистической погрешностью

2023-11-23 20:41 UTC, MrsSbr commented on group_9/flegel.dmitrii/lab3/src/test/java/ProductionInfoTest.java
> +import java.util.*;
попровьте в настройках идеи, чтобы она вам не сворачивала в *

2023-11-24 17:44 UTC, neuron1st commented on group_9/flegel.dmitrii/lab3/pom.xml
> +                    <source>8</source>
я внес микроправки 
![image](https://github.com/MrsSbr/amm-java-9-91/assets/128036949/4e29d7e6-81e3-4668-98c5-e631bd5cf68a)

2023-11-26 18:44 UTC, MrsSbr approved these changes

2023-11-26 18:45 UTC, merged