add lab2 of denisov nikita
MrsSbr/amm-java-9-91 pull request #56
Opened 2023-10-04 16:58 UTC by FaraneysX

2023-10-15 19:39 UTC, MrsSbr requested changes

2023-10-15 19:39 UTC, MrsSbr commented on group_9/denisov.nikita/lab2/src/Vehicle/Motorbike.java
> +    double fuelCapacity;
Какой модификатор доступа тут?

2023-10-15 19:39 UTC, MrsSbr commented on group_9/denisov.nikita/lab2/src/Vehicle/VehicleInterface.java
>  public interface VehicleInterface {
нейминг не по конвеншену. и по смыслу тоже не очень

2023-11-04 16:35 UTC, FaraneysX commented on group_9/denisov.nikita/lab2/src/Vehicle/Motorbike.java
> +    double fuelCapacity;
private package

2023-11-16 05:29 UTC, merged