Ivakin daniil lab2
MrsSbr/amm-java-9-91 pull request #81
Opened 2023-10-15 12:11 UTC by IDVIDV

2023-10-15 20:57 UTC, MrsSbr requested changes
Вообще прям классно, поправьте именование и напишите мне, выдам вам следующую лабу

2023-10-15 20:57 UTC, MrsSbr commented on group_9/ivakin.daniil/lab2/src/CatBreed/AnimalAction.java
> +public interface AnimalAction {
Очень кривое название

2023-10-15 20:57 UTC, MrsSbr commented on group_9/ivakin.daniil/lab2/src/Main.java
>  public class Main {
название не отражает сути класса

2023-10-15 21:22 UTC, IDVIDV commented on group_9/ivakin.daniil/lab2/src/Main.java
>  public class Main {
Про main понял, а название интерфейса тоже нужно поменять?

2023-10-15 21:26 UTC, MrsSbr commented on group_9/ivakin.daniil/lab2/src/Main.java
>  public class Main {
Да. Возможно не стоит путать тёплое с мягким,  а вынести методы в абстрактный класс. А интерфейс сделать , например, для диких кошек (охотиться или хищник)

2023-10-15 21:46 UTC, IDVIDV commented on group_9/ivakin.daniil/lab2/src/Main.java
>  public class Main {
Я думаю интерфейс AnimalAction имеет право быть, потому что в нем все-таки заложено только поведение животных / действия которые с ними можно сделать (tryPet), а состояния он никакого не хранит. Переименовать я мог бы в AnimalActivity (другое а голову не приходит). Так же его можно было бы разделить на два интерфейса: то, что делают животные, и то, что можно сделать с животным.

2023-10-15 21:53 UTC, MrsSbr commented on group_9/ivakin.daniil/lab2/src/Main.java
>  public class Main {
Может ли кто-то другой, кроме животного реализовывать этот интерфейс? 
Если нет, то зачем его делать, если все методы можно добавить в абстракный класс (который к слову, единственный реализует этот интерфейс)? Чтобы выполнить задание?

2023-10-15 21:58 UTC, IDVIDV commented on group_9/ivakin.daniil/lab2/src/Main.java
>  public class Main {
Хорошо, но тогда возникает проблема с интерфейсом хищника, потому что кроме животных я не знаю, кто еще может охотиться, и тогда получается этот интерфейс тоже нужно как-то скомбинировать с абстрактным классом животного

2023-10-15 22:02 UTC, MrsSbr commented on group_9/ivakin.daniil/lab2/src/Main.java
>  public class Main {
Не все животные хищники(например корова) и не все хищники животные (например хищные растения). И в данном случае важнее даже первое

2023-10-15 22:05 UTC, IDVIDV commented on group_9/ivakin.daniil/lab2/src/Main.java
>  public class Main {
Ну с животными понятно, что будет сначала общий класс животного, а потом от него наследоваться класс хищного животного, корова в таком случае может  напрямую наследоваться от животного, либо еще от одного посредника,например травоядного животного. А вот с хищным растениями получается только два класса, реализующих интерфейс хищника?

2023-10-15 22:29 UTC, IDVIDV commented on group_9/ivakin.daniil/lab2/src/Main.java
>  public class Main {
И если порассуждать о растениях, то они тоже живые и тоже питаются, только по-своему, через корни. Получается в таком случае можно ли отнести действие eat к интерфейсу, например, AliveCreature, потому что его выполняют живые существа из двух разных царств, или это тоже должно быть отнесено к абстрактному классу, потому что кроме живых существ больше никто не питается. В таком случае у меня только на усм приходит интерфейс, описывающий метод старения, например животные стареют биологически, у них развиваются болезни и т.п., а из неживого, например, лист металла - стареет физически, ржавчиной покрывается

2023-10-18 22:29 UTC, MrsSbr approved these changes

2023-10-18 22:29 UTC, merged